site_name: Explang Documentation Site
site_url: "https://github.com/opsit-io/opsit-explang-docs"

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
# add attributes like {: style='color: red;' }      
  - attr_list
  - def_list
      

nav:
  - "Explang Home": index.md
  - "Explang Goals and Features" : explang-goals-and-features.md
  - "Explang Core Quick Start" : explang-core-quick-start.md  
  - "Using Explang with Algebraic Syntax" : explang-alg.md
  - "Calling Explang from Java" : explang-from-java.md
  - "Extending Explang in Java" : explang-extending.md
  - "Explang/Alg funcs by Package": explang-alg-funcs-by-package.md
  - "Explang/Alg funcs by Name": explang-alg-funcs-by-name.md
  - "Explang/Alg Examples": explang-examples-alg.md            
  - "Using Explang with Lisp Syntax" : explang-lisp.md
  - "Explang/Lisp funcs by Package": explang-lisp-funcs-by-package.md
  - "Explang/Lisp funcs by Name": explang-lisp-funcs-by-name.md
  - "Explang/Lisp Examples": explang-examples-lisp.md
  - "Using Explang REPL" : using-explang-REPL.md

  - License: LICENSE.md

theme:
  name: material
  #readthedocs
  custom_dir: explang_theme/
  logo: site_logo.png
  highlightjs: true
  features:
    - navigation.sections
    
plugins:
  - markdownextradata

extra:
  explang:
    version: !ENV EXPLANG_VERSION
