site_name: Explang Documentation Site
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
# add attributes like {: style='color: red;' }      
  - attr_list
  - def_list
      

nav:
  - "Explang Home": index.md
  - "Explang Goals and Features" : explang-goals-and-features.md
  - "Using Explang with Algebraic Syntax" : explang-alg.md
  - "Calling Explang from Java" : explang-from-java.md
  - "Extending Explang in Java" : explang-extending.md
  - "Explang/Alg funcs by Package": explang-alg-funcs-by-package.md
  - "Explang/Alg funcs by Name": explang-alg-funcs-by-name.md
  - "Using Explang with Lisp Syntax" : explang-lisp.md
  - "Explang/Lisp funcs by Package": explang-lisp-funcs-by-package.md
  - "Explang/Lisp funcs by Name": explang-lisp-funcs-by-name.md    

  - License: LICENSE.md

theme:

  name: readthedocs
  custom_dir: explang_theme/
  logo: site_logo.png
  features:
    - navigation.sections
    
