site_name: Explang Documentation Site
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
# add attributes like {: style='color: red;' }      
  - attr_list
  - def_list
      

nav:
  - Home: index.md
  - License: LICENSE.md
  - "Explang/Lisp funcs by Package": explang-lisp-funcs-by-package.md
  - "Explang/Lisp funcs by Name": explang-lisp-funcs-by-name.md    
  - "Explang/Alg funcs by Package": explang-alg-funcs-by-package.md
  - "Explang/Alg funcs by Name": explang-alg-funcs-by-name.md    
    
theme:
  name: readthedocs
  features:
    - navigation.sections
    
